### ISSUE TITLE
Data Normalisation

### ISSUE THREAD

**Issue by NMontanaBrown** [joeranbosma/Hamlyn2021#8]

**Comment by joeranbosma** [comment]
The vast majority of depths lie within the range [0, 300]:
![image](https://user-images.githubusercontent.com/5995183/145199474-37ea29c7-02c2-4aa9-a337-63de37b11021.png)

Only 8 pixels have depths that exceed this (0.0000003456858%). I think normalising by dividing by 300 and clipping to [0, 1] is sufficient. This has the advantage that the depth labels are still linearly scaled, and interpretation is easy. 

Do we want to alter the distribution? For example, make it uniform or Gaussian?

**Comment by NMontanaBrown** [comment]
Thanks for looking at this - nice analysis. For now lets not alter the distribution? Seems like a highly skewed learning problem, looking at the peak and distr, will be interesting if learnable as is?

**Comment by NMontanaBrown** [comment]
Wait, are there functions to get rid of the pixels past 300 depth? I meant more as in the distribution after what you said.

**Comment by joeranbosma** [comment]
The depths > 300 are now clipped to 300
